### ISSUE TITLE
Add time control info

### ISSUE THREAD

**Issue by godmoves** [Tencent/PhoenixGo#16]
By default, the GTP command `time_settings` is listed but not enabled. 
If you want to use it, you will need to add
```
time_control {
    enable: 1
}
```
into the configure file.
I think you @wodesuck  should add this info into readme : )

PS: the `timeout_ms_per_step` looks like the upper limit of boyomi time per move, and any time setting larger than this will be set to this value.

**Comment by wodesuck** [comment]
Thanks for your remind, I will add it.

There are some other complicate logic in `MCTSEngine::GetSearchTimeoutUs` to decide how many time will use. To use `time_settings`, I think `time_control -> c_denom` and `time_control -> c_maxply` may also be set to avoid nan.

The real upper limit is `timeout_ms_per_step * max(unstable_overtime.time_factor, behind_overtime.time_factor)`,  since `xxx_overtime` options may make it cost more time in some situations. Btw, time less than `timeout_ms_per_step` may cost if `early_stop` is enable.

**Comment by godmoves** [comment]
Thank you for your reply.
