### ISSUE TITLE
Help with CPU version config file

### ISSUE THREAD

**Issue by Lecale** [Tencent/PhoenixGo#61]
First, thanks for releasing PhoenixGo.
I would like to use the CPU version to play handicap games. However, it will resign on move 1 if I set it up at 5 handicap stones. Can you give me some hints on how to alter the starting command line?
Some of the parameters, I am not sure what they mean.
If the program is not suited to handicap games, what is the best change to make to reduce its strength? Which options do you recommend to change in config file?

Thanks!

**Comment by alreadydone** [comment]
Sorry for the self-promotion but as for handicap games, the dynamic komi approach (implemented by myself for Leela Zero in https://github.com/gcp/leela-zero/pull/1772) seems to be the state-of-art. On a single 1080ti it's capable of giving 4 handicap stones to Chinese amateur 6-dans (there are only 300-400ish of them) with appropriate parameters, and doesn't act crazily at high handicap. I would like to see the PhoenixGo team implement the same approach, since their unreleased network is so strong, but if the network is too strong some training with games of different komi might be necessary for dynamic komi to work.
