### ISSUE TITLE
PhoenixGo crash at move 3 (reproductible)

### ISSUE THREAD

**Issue by wonderingabout** [Tencent/PhoenixGo#93]
i am a regular bot admin of native PhoenixGo, and i really love this AI for its game style :100: :1st_place_medal: , so i run it on OGS with these accounts for a long time already : 

- https://online-go.com/player/592558/meta-%E9%87%91%E6%AF%9B%E6%B5%8B%E8%AF%95-20b
- https://online-go.com/player/596107/meta-%E9%87%91%E6%AF%9B%E6%B5%8B%E8%AF%95-20b-Strong

but, as explained in this issue https://github.com/online-go/gtp2ogs/issues/190 , today i had an issue i never had before with gtp2ogs

a reproductible crash on game 3, 2 games on a row
is there a reason why PhoenixGo would crash ?

@wodesuck @zxkyjimmy 
big thanks :+1:

**Comment by wodesuck** [comment]
Could you run PhoenixGo with --v=1 and reproduce the issue?
***
```
May 03 20:52:18   bot.js:214                     [23183] >>> play white d4
May 03 20:52:18   game.js:490                    [Game 17708541]  Move 2    makeMove 2 is 2 !== 2 ?
May 03 20:52:18   bot.js:214                     [23183] Generating move for game 17708541
May 03 20:52:18   game.js:490                    [Game 17708541]  Move 2    genmove black
May 03 20:52:18   bot.js:214                     [23183] >>> genmove black
May 03 20:52:18   connection.js:1391             #  active_game: {"id":17708541,"phase":"play","name":"10000 vs 3200 test","player_to_move":592558,"width":19,"height":19,"move_number":2,"paused":0,"private":false,"black":{"username":"meta-金毛测试-20b","id":592558,"rank":19,"professional":false,"accepted":false,"ratings":{"overall":{"deviation":95.45099520611241,"rating":2760.424660297423,"volatility":0.060090145513783985,"games_played":23}}},"white":{"username":"RoyalZero","id":484523,"rank":25,"professional":false,"accepted":false,"ratings":{"overall":{"deviation":85.7766431653554,"rating":2818.0212415578553,"volatility":0.06260142409950183,"games_played":6201}}},"time_per_move":63}
May 03 20:52:18   connection.js:1391             #  Connected to game 17708541 already
May 03 20:52:57 !!!!! bot.js:222                     [23183] stderr: 3th move(b): dd, winrate=84.019028%, N=1305, Q=0.680381, p=0.093162, v=0.601550, cost 43920.070312ms, sims=10032, height=11, avg_height=5.028920, global_step=639200
May 03 20:52:57   bot.js:214                     [23183] <<< = D4
May 03 20:52:57   game.js:490                    [Game 17708541]  Move 2    Playing d4 { x: 3, y: 15, text: 'd4', resign: false, pass: false }
May 03 20:52:57 !!!!! bot.js:222                     [23183] stderr: F0503 20:52:57.935942 23183 mcts_engine.cc:154] Check failed: ret == 0 (-1 vs. 0) Move: failed, dd, ret-1
May 03 20:52:57 !!!!! bot.js:222                     [23183] stderr: *** Check failure stack trace: ***
May 03 20:52:57 !!!!! bot.js:222                     [23183] stderr: *** Aborted at 1556909577 (unix time) try "date -d @1556909577" if you are using GNU date ***
May 03 20:52:57 !!!!! bot.js:222                     [23183] stderr: PC: @                0x0 (unknown)
```
As what I could see from these logs, I guess your gtp2ogs might accidentally feed the second move which is `play white d4` into PhoenixGo before the `genmove` command, making those two moves colliding.

**Comment by wonderingabout** [comment]
@wodesuck 
i tried to reproduce the issue yesterday but i could not

your explanation makes sense and it is indeed possible

i will try to reproduce it again today and keep you updated :+1: 
thanks :+1: 

edit : also it is weird that **winrate is 84% at move 3**, isnt it because phoenixgo assume it was a pass ?

**Comment by roy7** [comment]
Interesting. The lines with ">>>" are what was sent to the bot. So the bot was told "play white d4" and then "genmove black" but the bot came back with a move on D4 which is illegal since white already just moved there. And the 84% win rate is because the bot thinks it moved twice in a row. So somehow the white d4 move didn't get seen by the bot.

**Comment by roy7** [comment]
I embedded the relevant code sections here https://github.com/online-go/gtp2ogs/issues/190#issuecomment-489434660. I think it's all non-async code. Since gtp2ogs log shows the play was sent before the genmove, I imagine it had to have been sent to the bot first. Unless there's some further complexity at a lower level in gtp2ogs I'm missing.

**Comment by roy7** [comment]
I asked @wonderingabout to manually do a genmove and then a play command for the same move the bot just made, to see if it will cause the crash reported in the log. If so then the problem is that the play and genmove gtp commands were processed in the wrong order. ATM I don't see how it'd be possible for gtp2ogs to send them in the wrong order though.

Given a play and a genmove gtp command effectively back to back with no delay, is there any possibility PhoenixGo could read them out of order? If stdin processing is multi-threaded or something?

**Comment by wonderingabout** [comment]
@wodesuck 

just had the issue yesterday again as JBXLeelaBot made me notice : 

https://online-go.com/game/17733237

too bad i didnt save command line log
i'll be running with `--v=1` from now on to debug this :+1: 

since it is now the 3rd time, it will definitely happen again :+1:

**Comment by wonderingabout** [comment]
@wodesuck got an error again

see full log in : https://github.com/online-go/gtp2ogs/issues/190#issuecomment-513558394

thanks :+1:

**Comment by wonderingabout** [comment]
solved in https://github.com/online-go/gtp2ogs/pull/197 :1st_place_medal:
